seed: 42
# SPLIT TEMPORAL ------------------------------------------------

train_end: 2022-12-31
val_start: 2023-01-01
val_end: 2024-05-31
test_start: 2024-06-01
test_end: 2024-12-31

# TRAINING ------------------------------------------------

total_timesteps: 1_000_000
checkpoint_every: 100_000
batch_size: 512
n_steps: 1024
gamma: 0.99
learning_rate: 5e-4
clip_range: 0.3
ent_coef: 0.005
